use std::{
    env, fs, io,
    path::{Path, PathBuf},
};

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let cases_root = manifest_dir.join("tests/cases");
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    let out_file = out_dir.join("ciel_case_tests.rs");

    let mut paths = Vec::new();
    collect_ciel_files(&cases_root, &mut paths).unwrap_or_else(|error| {
        panic!(
            "failed to collect Ciel fixture cases from `{}`: {error}",
            cases_root.display()
        )
    });
    paths.sort();

    let mut generated = String::new();
    generated.push_str("// @generated by build.rs; do not edit by hand.\n\n");

    for path in paths {
        println!("cargo:rerun-if-changed={}", path.display());
        let rel = path
            .strip_prefix(&cases_root)
            .unwrap_or(&path)
            .to_string_lossy()
            .replace('\\', "/");
        let Some(kind) = case_kind(&path) else {
            continue;
        };
        if !is_active_case_kind(&kind) {
            continue;
        }

        let name = test_name(&rel);
        generated.push_str("#[test]\n");
        generated.push_str(&format!("fn {name}() {{\n"));
        generated.push_str(&format!("    super::run_generated_case({rel:?});\n"));
        generated.push_str("}\n\n");
    }

    fs::write(&out_file, generated).unwrap_or_else(|error| {
        panic!(
            "failed to write generated Ciel fixture tests to `{}`: {error}",
            out_file.display()
        )
    });
}

fn collect_ciel_files(dir: &Path, out: &mut Vec<PathBuf>) -> io::Result<()> {
    println!("cargo:rerun-if-changed={}", dir.display());
    for entry in fs::read_dir(dir)? {
        let entry = entry?;
        let path = entry.path();
        if path.is_dir() {
            collect_ciel_files(&path, out)?;
        } else if path.extension().and_then(|ext| ext.to_str()) == Some("ciel") {
            out.push(path);
        }
    }
    Ok(())
}

fn case_kind(path: &Path) -> Option<String> {
    let source = fs::read_to_string(path).ok()?;
    for line in source.lines() {
        let Some(comment) = line.trim_start().strip_prefix("//") else {
            continue;
        };
        let Some((key, raw_value)) = comment.trim_start().split_once(':') else {
            continue;
        };
        if key.trim() == "ciel-test" {
            return Some(raw_value.trim().to_string());
        }
    }
    None
}

fn is_active_case_kind(kind: &str) -> bool {
    !matches!(kind, "dependency" | "manual")
}

fn test_name(rel: &str) -> String {
    let mut name = String::from("case_");
    let mut previous_was_separator = false;
    for ch in rel.trim_end_matches(".ciel").chars() {
        if ch.is_ascii_alphanumeric() {
            name.push(ch.to_ascii_lowercase());
            previous_was_separator = false;
        } else if !previous_was_separator {
            name.push('_');
            previous_was_separator = true;
        }
    }
    if name.ends_with('_') {
        name.pop();
    }
    name.push('_');
    name.push_str(&format!("{:016x}", stable_hash(rel)));
    name
}

fn stable_hash(text: &str) -> u64 {
    let mut hash = 0xcbf29ce484222325u64;
    for byte in text.bytes() {
        hash ^= u64::from(byte);
        hash = hash.wrapping_mul(0x100000001b3);
    }
    hash
}
