use super::*;

impl<'a> CGenerator<'a> {
    pub(super) fn emit(mut self) -> DiagResult<String> {
        let _escape_summary_count = self.escapes.functions.len();

        self.emit_header_prelude();
        self.emit_string_literal_table();
        self.emit_forward_type_declarations();
        self.emit_slice_type_declarations();
        self.emit_layout_and_helper_sections();
        self.emit_support_prototypes();
        self.emit_generated_support_bodies()?;
        self.emit_user_functions()?;
        self.emit_entrypoint();

        Ok(std::mem::take(&mut self.out))
    }

    fn emit_header_prelude(&mut self) {
        self.line("/* generated by cielc */");
        self.emit_runtime();
        self.line("");
        self.emit_c_includes();
        self.line("");
        self.emit_source_location_table();
        self.emit_meta_type_tag_type();
    }

    fn emit_meta_type_tag_type(&mut self) {
        self.line("typedef struct { char _ciel_empty; } CielMetaTypeTag;");
        self.line("");
    }

    fn emit_string_literal_table(&mut self) {
        for (key, raw) in self.plan.string_literals.clone() {
            let name = self
                .plan
                .string_literal_names
                .get(&key)
                .cloned()
                .unwrap_or_else(|| self.next_temp("str"));
            self.line(&format!("static const char {name}[] = {raw};"));
        }
        if !self.plan.string_literals.is_empty() {
            self.line("");
        }
    }

    fn emit_forward_type_declarations(&mut self) {
        self.emit_dynamic_type_forward_declarations();
        self.emit_closure_forward_declarations();
        self.emit_aggregate_forward_declarations();
    }

    fn emit_dynamic_type_forward_declarations(&mut self) {
        for (name, ty) in self.plan.dynamic_types.clone() {
            let vtable = self.dynamic_vtable_name(&ty);
            self.line(&format!("typedef struct {vtable} {vtable};"));
            self.line(&format!(
                "typedef struct {{ void *data; const {vtable} *vtable; }} {name};"
            ));
        }
        if !self.plan.dynamic_types.is_empty() {
            self.line("");
        }
    }

    fn emit_closure_forward_declarations(&mut self) {
        for name in self.plan.closure_types.keys().cloned().collect::<Vec<_>>() {
            self.line(&format!("typedef struct {name} {name};"));
        }
        for closure in self.plan.closure_defs.values().cloned().collect::<Vec<_>>() {
            if !closure.captures.is_empty() {
                let env_name = self.closure_env_name(closure.owner, closure.id);
                self.line(&format!("typedef struct {env_name} {env_name};"));
            }
        }
        for wrapper in self
            .plan
            .function_closure_wrappers
            .values()
            .cloned()
            .collect::<Vec<_>>()
        {
            let env_name =
                self.function_closure_env_name(&wrapper.closure_ty, &wrapper.function_ty);
            self.line(&format!("typedef struct {env_name} {env_name};"));
        }
        for wrapper in self
            .plan
            .retained_closure_wrappers
            .values()
            .cloned()
            .collect::<Vec<_>>()
        {
            let env_name = self.retained_closure_env_name(&wrapper.target_ty, &wrapper.source_ty);
            self.line(&format!("typedef struct {env_name} {env_name};"));
        }
        if !self.plan.closure_types.is_empty()
            || !self.plan.closure_defs.is_empty()
            || !self.plan.function_closure_wrappers.is_empty()
            || !self.plan.retained_closure_wrappers.is_empty()
        {
            self.line("");
        }
    }

    fn emit_aggregate_forward_declarations(&mut self) {
        for opaque in &self.program.checked.opaque_structs {
            self.line(&format!("typedef struct {} {};", opaque.name, opaque.name));
        }
        for strukt in &self.program.checked.structs {
            self.line(&format!("typedef struct {} {};", strukt.name, strukt.name));
        }
        for enm in &self.program.checked.enums {
            self.line(&format!("typedef struct {} {};", enm.name, enm.name));
        }
        for name in self
            .plan
            .array_return_types
            .keys()
            .cloned()
            .collect::<Vec<_>>()
        {
            self.line(&format!("typedef struct {name} {name};"));
        }
        if !self.program.checked.opaque_structs.is_empty()
            || !self.program.checked.structs.is_empty()
            || !self.program.checked.enums.is_empty()
            || !self.plan.array_return_types.is_empty()
        {
            self.line("");
        }
    }

    fn emit_slice_type_declarations(&mut self) {
        let mut emitted_slice_type = false;
        for (slice, ty) in self.plan.slice_types.clone() {
            if prelude_defines_slice_type(&slice) {
                continue;
            }
            let Ty::Slice { mutability, elem } = ty else {
                continue;
            };
            let ptr_decl = self.c_decl(
                &Ty::Pointer {
                    nullable: false,
                    mutability,
                    inner: elem,
                },
                "ptr",
            );
            self.line(&format!(
                "typedef struct {{ {ptr_decl}; size_t len; }} {slice};"
            ));
            emitted_slice_type = true;
        }
        if emitted_slice_type {
            self.line("");
        }
    }

    fn emit_layout_and_helper_sections(&mut self) {
        self.emit_closure_value_layouts();

        for aggregate in self.aggregate_layout_order() {
            match aggregate {
                AggregateLayoutRef::Struct(idx) => self.emit_struct_layout(idx),
                AggregateLayoutRef::Enum(idx) => self.emit_enum_layout(idx),
            }
        }

        self.emit_array_return_type_layouts();
        self.emit_resource_cleanup_helpers();
        self.emit_resource_transfer_helpers();

        self.emit_async_function_contexts();
        self.emit_async_closure_contexts();
        self.emit_async_sleep_future_contexts();
        self.emit_async_op_future_contexts();
        self.emit_async_channel_future_contexts();

        self.emit_closure_environment_layouts();
        self.emit_dynamic_vtable_layouts();
    }

    fn emit_support_prototypes(&mut self) {
        let mut emitted_prototypes = HashSet::new();
        for function in &self.program.checked.functions {
            let prototype = format!("{};", self.function_decl(function, true));
            if emitted_prototypes.insert(prototype.clone()) {
                self.line(&prototype);
            }
        }

        self.emit_closure_prototypes();
        self.emit_retained_closure_witness_prototypes();
        self.emit_actor_dispatch_prototypes();
        self.emit_async_function_run_prototypes();
        self.emit_async_closure_run_prototypes();
        self.emit_async_sleep_future_prototypes();
        self.emit_async_op_future_prototypes();
        self.emit_async_channel_future_prototypes();
        self.emit_dynamic_shim_prototypes();
        self.line("");
    }

    fn emit_generated_support_bodies(&mut self) -> DiagResult<()> {
        self.emit_dynamic_shims_and_tables();
        if !self.plan.dynamic_impls.is_empty() {
            self.line("");
        }

        self.emit_closure_thunks_and_wrappers()?;
        if !self.plan.closure_defs.is_empty()
            || !self.plan.function_closure_wrappers.is_empty()
            || !self.plan.retained_closure_wrappers.is_empty()
        {
            self.line("");
        }

        self.emit_retained_closure_witnesses()?;
        if !self.plan.retained_closure_witnesses.is_empty() {
            self.line("");
        }

        self.emit_actor_dispatches()?;
        if !self.plan.actor_dispatches.is_empty() {
            self.line("");
        }

        self.emit_async_sleep_future_runs()?;
        if !self.plan.async_sleep_output_tys.is_empty() {
            self.line("");
        }

        self.emit_async_op_future_runs()?;
        if !self.plan.async_op_contexts.is_empty() {
            self.line("");
        }

        self.emit_async_channel_future_runs()?;
        if !self.plan.async_channel_send_payload_tys.is_empty()
            || !self.plan.async_channel_reserve_payload_tys.is_empty()
            || !self.plan.async_channel_recv_payload_tys.is_empty()
        {
            self.line("");
        }

        Ok(())
    }

    fn emit_user_functions(&mut self) -> DiagResult<()> {
        let functions = self.program.checked.functions.clone();
        for function in &functions {
            if function.body.is_some() {
                self.gen_function(function)?;
                self.line("");
            }
        }
        Ok(())
    }

    fn emit_entrypoint(&mut self) {
        if let Some(main_id) = self.find_ciel_main().map(|main| main.def_id) {
            self.line("int main(int argc, char **argv) {");
            self.line("    ciel_runtime_init();");
            self.line("    ciel_runtime_set_args(argc, argv);");
            self.line(&format!("    return (int){}();", self.c_name(main_id)));
            self.line("}");
        }
    }
}
