pub mod affine;
pub mod ast;
pub mod build;
pub mod capture;
pub mod checked;
pub mod ciel_display;
pub mod codegen;
pub mod common;
pub mod diagnostic;
pub mod driver;
pub mod escape;
pub mod formatter;
pub mod hir;
pub mod interfaces;
pub mod layout;
pub mod lexer;
pub mod lsp;
pub mod mono;
pub mod parser;
pub mod resolve;
pub mod retained;
pub mod source;
pub mod span;
pub mod std_id;
pub mod suggest;
pub mod thir;
pub mod tree_sitter_ciel;
pub mod type_display;
pub mod typeck;
pub mod types;

pub use build::{BuildPlan, BuildProfile};
pub use diagnostic::{DiagResult, Diagnostic, DiagnosticPhase, WithDiagnostics};
pub use driver::{CompileOptions, compile_to_build_plan, compile_to_c};
