pub mod ast;
pub mod capture;
pub mod codegen;
pub mod diagnostic;
pub mod driver;
pub mod escape;
pub mod hir;
pub mod interfaces;
pub mod lexer;
pub mod mono;
pub mod parser;
pub mod resolve;
pub mod retained;
pub mod source;
pub mod span;
pub mod std_id;
pub mod thir;
pub mod typeck;
pub mod types;

pub use diagnostic::{DiagResult, Diagnostic};
pub use driver::{CompileOptions, compile_to_c};
